a=int(input("Enter the first number:"))
b=int(input("Enter the second number:")) 
sum=a+b
print("sum=", sum)
difference=a-b
print("difference=", difference)
multiplication=a*b
print("multiplication=",multiplication)
division=a/b
print("division=",division)